import terminal from "../generated/terminal.html?raw";

/**
 * Real reporter output: the Base → Arbitrum Across e2e from the repo, replayed offline and
 * printed by @condensate_dev/forkit/reporter. Generated by site/tools/build-assets.ts (the report's
 * ANSI colours as spans, text HTML-escaped), never hand-edited.
 */
export function Terminal() {
  return (
    <figure className="fk-terminal">
      <div className="fk-terminal-bar" aria-hidden="true">
        <span />
        <span />
        <span />
        <em>bun run test:e2e</em>
      </div>
      {/* biome-ignore lint/security/noDangerouslySetInnerHtml: generated from the repo's own test run, escaped by build-assets.ts. */}
      <div className="fk-terminal-body" dangerouslySetInnerHTML={{ __html: terminal }} />
      <figcaption>
        Real output: the Base → Arbitrum Across test from the repo, replayed offline.
      </figcaption>
    </figure>
  );
}
